basedir: file:./config
start-url: https://api.github.com/users/technoweenie
endpoints: ${basedir}/endpoints.yml

logging:
  level:
    org.apache.commons.beanutils: WARN
    org.shake.linkcheck: DEBUG
