baseprotocol: "file:"
basedir: ./config
fullbasedir: ${baseprotocol}${basedir}

start-url: https://api.github.com/users/anshake
api-endpoints: ${fullbasedir}/endpoints.yml

output:
  report: ${fullbasedir}/out/report.tsv

logging:
  level:
    org.apache.commons.beanutils: WARN
    org.shake.linkcheck: DEBUG
#  file: ${basedir}/log/line-checker.log

spring:
  jmx:
    enabled: false