start-url: https://api.github.com/users/anshake

setup:
  endpoints:
    /anshake:
        method: GET
        fields:
        - url
        - followers_url
        headers:
          Content-Type: application/json
          x-type: abcd;
        body: '
              {
                "abc" : 123,
                "a1": "s2"
              }'
    /subbase/endpoint2:
        method: GET
        fields:
        - links.nested.link