setup:
  start:
    url: https://api.github.com/users/anshake
    method: GET
  endpoints:
    - url: /**/anshake
      method: GET
      fields:
      - url
      - followers_url
    - url: /users/anshake
      method: GET
      fields:
      - links.nested.link